# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=128)),
                ('exchange', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=32)),
                ('category_name', models.CharField(max_length=128)),
                ('category_number', models.CharField(max_length=3)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
